// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MvvmCrossApp.Core.Models;
using UIKit;

namespace MvvmCrossApp.iOS.Views
{
	public partial class MedicineCell : UITableViewCell
	{
		public MedicineCell(IntPtr handle) : base(handle)
		{
		}

		public void UpdateCell(List<Medicines> medicines, NSIndexPath indexPath)
		{
			MedicineLabel.Text = medicines[indexPath.Row].Nombre;
		}
	}
}
